"""Server-side PDF manipulation: field stamping, watermarking, certificate page.

Coordinates arriving from the workflow builder are normalised (0..1) with a
top-left origin, matching how the browser lays fields over a rendered page.
PDF user space is bottom-left origin, so every y is flipped here.
"""

from __future__ import annotations

import base64
import io
from dataclasses import dataclass

from pypdf import PdfReader, PdfWriter
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas as pdf_canvas

SIGNATURE_FONT = "Times-Italic"
BODY_FONT = "Helvetica"
BOLD_FONT = "Helvetica-Bold"
MONO_FONT = "Courier"

ACCENT = colors.HexColor("#0040e0")
INK = colors.HexColor("#191c1e")
MUTED = colors.HexColor("#515f74")
HAIRLINE = colors.HexColor("#c4c5d9")


@dataclass
class StampField:
    page: int          # 0-based
    x: float           # normalised left
    y: float           # normalised top
    width: float       # normalised
    height: float      # normalised
    kind: str          # signature | initials | date | text | checkbox
    value: str
    label: str = ""


def page_count(data: bytes) -> int:
    return len(PdfReader(io.BytesIO(data)).pages)


def _draw_image_value(c, value: str, x, y, w, h) -> bool:
    """Draw a data-URL PNG (a hand-drawn signature) fitted inside the box."""
    try:
        header, _, b64 = value.partition(",")
        if "image" not in header or not b64:
            return False
        image = ImageReader(io.BytesIO(base64.b64decode(b64)))
        iw, ih = image.getSize()
        scale = min(w / iw, h / ih) if iw and ih else 1
        dw, dh = iw * scale, ih * scale
        c.drawImage(
            image, x + (w - dw) / 2, y + (h - dh) / 2, dw, dh,
            mask="auto", preserveAspectRatio=True,
        )
        return True
    except Exception:
        return False


def _fit_font_size(text: str, box_w: float, box_h: float, font: str, c) -> float:
    size = min(box_h * 0.62, 22)
    while size > 6 and c.stringWidth(text, font, size) > box_w * 0.94:
        size -= 0.5
    return max(size, 6)


def _stamp_page(c, width, height, fields, watermark_text):
    for field in fields:
        x = field.x * width
        w = max(field.width * width, 1)
        h = max(field.height * height, 1)
        y = height - (field.y * height) - h  # flip to bottom-left origin
        value = (field.value or "").strip()

        if field.kind == "checkbox":
            c.setStrokeColor(HAIRLINE)
            c.setLineWidth(1)
            box = min(w, h, 14)
            base_y = y + (h - box) / 2
            c.rect(x, base_y, box, box)
            if value.lower() in {"true", "1", "yes", "on", "checked"}:
                c.setStrokeColor(ACCENT)
                c.setLineWidth(1.8)
                c.line(x + box * 0.20, base_y + box * 0.50, x + box * 0.45, base_y + box * 0.22)
                c.line(x + box * 0.45, base_y + box * 0.22, x + box * 0.82, base_y + box * 0.75)
            continue

        if not value:
            continue

        if field.kind in {"signature", "initials"}:
            if not _draw_image_value(c, value, x, y, w, h):
                font_size = _fit_font_size(value, w, h, SIGNATURE_FONT, c)
                c.setFont(SIGNATURE_FONT, font_size)
                c.setFillColor(INK)
                c.drawString(x + 2, y + h * 0.34, value)
            c.setStrokeColor(HAIRLINE)
            c.setLineWidth(0.6)
            c.line(x, y + h * 0.22, x + w, y + h * 0.22)
            if field.label:
                c.setFont(BODY_FONT, 6.5)
                c.setFillColor(MUTED)
                c.drawString(x, y + h * 0.08, field.label[:60])
        else:
            font_size = _fit_font_size(value, w, h, BODY_FONT, c)
            c.setFont(BODY_FONT, font_size)
            c.setFillColor(INK)
            c.drawString(x + 2, y + (h - font_size) / 2 + 1, value)

    if watermark_text:
        c.saveState()
        c.setFont(BOLD_FONT, 9)
        c.setFillColor(ACCENT, alpha=0.55)
        c.drawCentredString(width / 2, 16, watermark_text)
        c.restoreState()


def _certificate(width, height, *, document, recipients, events) -> bytes:
    buf = io.BytesIO()
    c = pdf_canvas.Canvas(buf, pagesize=(width, height))
    margin = 54
    y = height - margin

    c.setFillColor(ACCENT)
    c.rect(0, height - 6, width, 6, stroke=0, fill=1)

    c.setFont(BOLD_FONT, 20)
    c.setFillColor(INK)
    c.drawString(margin, y - 14, "Certificate of Completion")
    y -= 38
    c.setFont(BODY_FONT, 9.5)
    c.setFillColor(MUTED)
    c.drawString(margin, y, "Tamper-evident record generated by DocuRoute")
    y -= 26

    def row(label, value, gap=15):
        nonlocal y
        c.setFont(BOLD_FONT, 8.5)
        c.setFillColor(MUTED)
        c.drawString(margin, y, label.upper())
        text = str(value)
        c.setFont(MONO_FONT if len(text) > 46 else BODY_FONT, 8.5)
        c.setFillColor(INK)
        c.drawString(margin + 150, y, text[:78])
        y -= gap

    row("Document", document.get("title", ""))
    row("Document ID", document.get("id", ""))
    row("Original SHA-256", document.get("original_hash", ""))
    row("Completed at", document.get("completed_at", ""))

    y -= 12
    c.setStrokeColor(HAIRLINE)
    c.setLineWidth(0.7)
    c.line(margin, y, width - margin, y)
    y -= 20

    c.setFont(BOLD_FONT, 11)
    c.setFillColor(INK)
    c.drawString(margin, y, "Signers")
    y -= 18
    for index, person in enumerate(recipients, start=1):
        c.setFont(BODY_FONT, 9)
        c.setFillColor(INK)
        c.drawString(margin, y, f"{index}. {person.get('name', '')} <{person.get('email', '')}>")
        c.setFillColor(MUTED)
        c.setFont(BODY_FONT, 8)
        parts = [
            person.get("role", ""),
            person.get("status", ""),
            str(person.get("completed_at") or "-"),
            "IP " + str(person.get("ip") or "-"),
        ]
        c.drawString(margin + 12, y - 10, " | ".join(parts)[:100])
        y -= 26
        if y < margin + 120:
            c.showPage()
            y = height - margin

    y -= 6
    c.setStrokeColor(HAIRLINE)
    c.line(margin, y, width - margin, y)
    y -= 20
    c.setFont(BOLD_FONT, 11)
    c.setFillColor(INK)
    c.drawString(margin, y, "Audit chain")
    y -= 16

    for event in events:
        if y < margin + 40:
            c.showPage()
            y = height - margin
        c.setFont(BODY_FONT, 8.5)
        c.setFillColor(INK)
        headline = f"#{event.get('seq')}  {event.get('event_type')}  -  {event.get('actor_label') or 'system'}"
        c.drawString(margin, y, headline[:96])
        c.setFont(MONO_FONT, 7)
        c.setFillColor(MUTED)
        c.drawString(margin + 12, y - 9, f"{event.get('created_at')}  {str(event.get('chain_hash', ''))[:56]}")
        y -= 22

    c.showPage()
    c.save()
    return buf.getvalue()


def build_final_pdf(
    source: bytes,
    fields: list[StampField],
    *,
    watermark_text: str = "",
    document: dict | None = None,
    recipients: list[dict] | None = None,
    events: list[dict] | None = None,
) -> bytes:
    """Flatten field values onto the source PDF, watermark it, append the certificate."""
    reader = PdfReader(io.BytesIO(source))
    writer = PdfWriter()

    by_page: dict[int, list[StampField]] = {}
    for field in fields:
        by_page.setdefault(int(field.page), []).append(field)

    for index, page in enumerate(reader.pages):
        box = page.mediabox
        width = float(box.width)
        height = float(box.height)
        page_fields = by_page.get(index, [])
        if page_fields or watermark_text:
            overlay_buf = io.BytesIO()
            c = pdf_canvas.Canvas(overlay_buf, pagesize=(width, height))
            _stamp_page(c, width, height, page_fields, watermark_text)
            c.save()
            overlay_buf.seek(0)
            page.merge_page(PdfReader(overlay_buf).pages[0])
        writer.add_page(page)

    if document is not None and len(reader.pages):
        first = reader.pages[0].mediabox
        cert = _certificate(
            float(first.width),
            float(first.height),
            document=document,
            recipients=recipients or [],
            events=events or [],
        )
        for page in PdfReader(io.BytesIO(cert)).pages:
            writer.add_page(page)

    writer.add_metadata(
        {
            "/Producer": "DocuRoute",
            "/Title": (document or {}).get("title", "Executed document"),
            "/Subject": f"DocuRoute document {(document or {}).get('id', '')}",
        }
    )
    out = io.BytesIO()
    writer.write(out)
    return out.getvalue()
