# Generated by Django 5.2.17 on 2026-09-02 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=16)),
                ('message', models.TextField(blank=True, help_text='Note included in every invitation email.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_days', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('signer', 'Needs to sign'), ('approver', 'Needs to approve'), ('viewer', 'Receives a copy')], default='signer', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Waiting for earlier steps'), ('sent', 'Invitation sent'), ('viewed', 'Opened the document'), ('completed', 'Completed'), ('declined', 'Declined')], db_index=True, default='pending', max_length=16)),
                ('token_jti', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_issued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_user_agent', models.CharField(blank=True, max_length=500)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials'), ('date', 'Date signed'), ('text', 'Text'), ('checkbox', 'Checkbox')], default='signature', max_length=16)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('page', models.PositiveSmallIntegerField(default=0)),
                ('x', models.FloatField(default=0.1)),
                ('y', models.FloatField(default=0.1)),
                ('width', models.FloatField(default=0.24)),
                ('height', models.FloatField(default=0.06)),
                ('required', models.BooleanField(default=True)),
                ('value', models.TextField(blank=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.document')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workflows.recipient')),
            ],
            options={
                'ordering': ['page', 'y', 'x'],
                'indexes': [models.Index(fields=['document', 'page'], name='workflows_f_documen_b87603_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['workflow', 'order'], name='workflows_r_workflo_3afb53_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.UniqueConstraint(fields=('workflow', 'email'), name='unique_recipient_email_per_workflow'),
        ),
    ]
