# Generated by Django 5.2.17 on 2026-09-02 05:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('document.created', 'Document created'), ('document.uploaded', 'File uploaded'), ('workflow.saved', 'Workflow saved'), ('workflow.sent', 'Sent for signature'), ('invitation.sent', 'Invitation sent'), ('document.viewed', 'Document viewed'), ('signature.applied', 'Signature applied'), ('recipient.approved', 'Approved'), ('recipient.declined', 'Declined'), ('document.executed', 'Document executed'), ('document.voided', 'Document voided'), ('document.downloaded', 'Document downloaded')], max_length=40)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('revision_sha256', models.CharField(blank=True, max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('prev_hash', models.CharField(max_length=64)),
                ('chain_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.recipient')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'seq'],
                'indexes': [models.Index(fields=['document', '-seq'], name='audit_audit_documen_e7cda0_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'seq'), name='unique_event_seq')],
            },
        ),
    ]
